language: php

php:
  - 8.2.9

before_install:
  - sudo apt-cache search libonig

install:
  - sudo apt-get update
  - sudo apt-get install -y libonig-dev
  - composer install --no-interaction

script:
  - vendor/bin/phpunit tests\unit\Support\NavigationAddPeriodTest.php

  - vendor/bin/phpunit tests\unit\Support\NavigationStartOfPeriodTest.php

  - vendor/bin/phpunit tests\unit\Support\Calendar\CalculatorProvider.php

  - vendor/bin/phpunit tests\unit\Support\Calendar\CalculatorTest.php

  - vendor/bin/phpunit tests\unit\Support\Calendar\Periodicity\BimonthlyTest.php

  - vendor/bin/phpunit tests\unit\Support\Calendar\Periodicity\DailyTest.php

  - vendor/bin/phpunit tests\unit\Support\Calendar\Periodicity\FortnightlyTest.php

  - vendor/bin/phpunit tests\unit\Support\Calendar\Periodicity\HalfYearlyTest.php

  - vendor/bin/phpunit tests\unit\Support\Calendar\Periodicity\IntervalProvider.php

  - vendor/bin/phpunit tests\unit\Support\Calendar\Periodicity\IntervalTestCase.php

  - vendor/bin/phpunit tests\unit\Support\Calendar\Periodicity\MonthlyTest.php

  - vendor/bin/phpunit tests\unit\Support\Calendar\Periodicity\QuarterlyTest.php

  - vendor/bin/phpunit tests\unit\Support\Calendar\Periodicity\WeeklyTest.php

  - vendor/bin/phpunit tests\unit\Support\Calendar\Periodicity\YearlyTest.php

branches:
  only:
    - main

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

notifications:
  email: false
