language: php

php:
  - 8.2.9

install:
  - sudo apt-get update
  - sudo apt-get install -y libonig5
  - composer install --no-interaction

before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit --configuration phpunit.xml

branches:
  only:
    - main

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

notifications:
  email: false
