language: php
php:
  - "7.4"  # Use the desired PHP version

# Cache Composer dependencies
cache:
  directories:
    - $HOME/.composer/cache

# Install project dependencies
install:
  - composer install

# Run PHPUnit tests
script:
  - ./vendor/bin/phpunit
